### Mutations modeled by Rosetta

* Look over the CHTC results that are stored in the sqlite DB (just scores)
* Create a test_train dataset
* Save the test set with redone rosetta terms

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

import rosetta_db

## Mutations from 2D parent

In [2]:
df = rosetta_db.get_energy_scores(parent="2D")

In [3]:
df.columns

Index(['r_total_score', 'r_dslf_fa13', 'r_fa_atr', 'r_fa_dun', 'r_fa_elec',
       'r_fa_intra_rep', 'r_fa_intra_sol_xover4', 'r_fa_rep', 'r_fa_sol',
       'r_hbond_bb_sc', 'r_hbond_lr_bb', 'r_hbond_sc', 'r_hbond_sr_bb',
       'r_lk_ball_wtd', 'r_omega', 'r_p_aa_pp', 'r_pro_close', 'r_rama_prepro',
       'r_ref', 'r_yhh_planarity', 'd_total_score', 'd_Grid_score',
       'd_Transform_accept_ratio', 'd_angle_constraint',
       'd_atom_pair_constraint', 'd_chainbreak', 'd_classic_grid_X',
       'd_coordinate_constraint', 'd_dihedral_constraint', 'd_dslf_ca_dih',
       'd_dslf_cs_ang', 'd_dslf_ss_dih', 'd_dslf_ss_dst', 'd_fa_atr',
       'd_fa_dun', 'd_fa_elec', 'd_fa_pair', 'd_fa_rep', 'd_fa_sol',
       'd_hbond_bb_sc', 'd_hbond_lr_bb', 'd_hbond_sc', 'd_hbond_sr_bb',
       'd_if_X_angle_constraint', 'd_if_X_atom_pair_constraint',
       'd_if_X_chainbreak', 'd_if_X_coordinate_constraint',
       'd_if_X_dihedral_constraint', 'd_if_X_dslf_ca_dih',
       'd_if_X_dslf_cs_ang', 'd_if_X_dslf_ss_dih', 'd_if_X_dslf_ss_dst',
       'd_if_X_fa_atr', 'd_if_X_fa_dun', 'd_if_X_fa_elec', 'd_if_X_fa_pair',
       'd_if_X_fa_rep', 'd_if_X_fa_sol', 'd_if_X_hbond_bb_sc',
       'd_if_X_hbond_lr_bb', 'd_if_X_hbond_sc', 'd_if_X_hbond_sr_bb',
       'd_if_X_omega', 'd_if_X_p_aa_pp', 'd_if_X_pro_close', 'd_if_X_ref',
       'd_interface_delta_X', 'd_ligand_is_touching_X', 'd_omega', 'd_p_aa_pp',
       'd_pro_close', 'd_ref', 'd_total_score_X', 'variant'],
      dtype='object')

In [4]:
df.head()

,r_total_score,r_dslf_fa13,r_fa_atr,r_fa_dun,r_fa_elec,r_fa_intra_rep,r_fa_intra_sol_xover4,r_fa_rep,r_fa_sol,r_hbond_bb_sc,...,d_if_X_pro_close,d_if_X_ref,d_interface_delta_X,d_ligand_is_touching_X,d_omega,d_p_aa_pp,d_pro_close,d_ref,d_total_score_X,variant
0,-857.943,0.0,-1563.589,316.642,-539.426,2.838,55.569,182.141,936.300,-57.349,...,0.0,0.0,-10.014,1.0,47.292,-40.692,1.027,-41.04,-30.0,D53W.V166Y.W196K
1,-853.451,0.0,-1566.619,320.550,-537.542,2.932,56.286,186.453,929.978,-55.907,...,0.0,0.0,-7.627,1.0,49.498,-41.948,1.125,-43.43,-30.0,A16K.N167I.A187M
2,-847.306,0.0,-1562.663,321.941,-540.116,2.886,56.374,181.451,931.672,-55.895,...,0.0,0.0,-8.558,1.0,48.730,-39.806,0.964,-39.23,-31.0,V43C.A73I.L137W
3,-862.828,0.0,-1561.831,318.629,-539.675,2.875,56.133,180.080,939.619,-57.035,...,0.0,0.0,-8.589,1.0,50.224,-41.688,1.038,-44.25,-28.0,V39E.Y213E.A247R
4,-846.302,0.0,-1558.842,320.008,-537.013,2.821,56.273,185.282,939.990,-57.288,...,0.0,0.0,-7.669,1.0,49.855,-42.352,1.008,-41.38,-29.0,K88L.L136E.A187H

In [5]:
# Number of mutations modeled
len(df)

100000

In [6]:
# campaign1_muts = [
#     'D157G.I71V.R172H.F152L.I38V.Q233R.F261L',
#     'D157G.I71V.R172H.F152L.I38V.Q233R.F261L.V38I.R48C',
#     'D157G.I71V.R172H.F152L',
#     'D157G.I71V.R172H.N65D',
#     'D157G.I71V.R172H',
#     'D157G.I71V',
#     'D157G'
# ]

## Create test_train split

In [7]:
# Set to True if we really want to replace
# Setting to False so that we do not accidentally overwrite
REPLACE_TEST_TRAIN_SPLIT = True
splits_dir = rosetta_db.get_splits_dir(parent="2D")

if REPLACE_TEST_TRAIN_SPLIT:
    np.random.seed(42)# set seed for test_training split
    train_df, test_df = train_test_split(df, test_size=0.1)
    
    train_df.reset_index(drop=True).to_pickle(splits_dir / "train_df.pkl")
    test_df.reset_index(drop=True).to_pickle(splits_dir / "test_df.pkl")
     
    train_df.variant.sort_values().to_csv(splits_dir / "train_variants.txt", 
                            header=False, index=False)
    test_df.variant.sort_values().to_csv(splits_dir / "test_variants.txt", 
                            header=False, index=False)

In [8]:
# Check the variants with the saved backup list of variants
# to make sure that nothing has changed
!diff {splits_dir}/train_variants.txt \
    {splits_dir}/backup/train_variants.sort.txt
!diff {splits_dir}/test_variants.txt\
    {splits_dir}/backup/test_variants.sort.txt

In [9]:
# the test set was redone a second time to account for
# stochasticty in the rosetta results
if REPLACE_TEST_TRAIN_SPLIT:

    test2_df = rosetta_db.get_energy_scores(parent="2D", 
                   table_name_postfix="_redo_test_set")
    test2_df.reset_index(drop=True).to_pickle(splits_dir / "test2_df.pkl")
    
    test2_df.variant.sort_values().to_csv(splits_dir / "test2_variants.txt", 
                            header=False, index=False)

In [10]:
!diff {splits_dir}/test2_variants.txt\
    {splits_dir}/backup/test_variants.sort.txt

### Looking at sum of energy terms

In [11]:
# drop the first r_energy term (r_total_score) and sum up the other r_ energy terms
# we should get something very close to the r_total_score
print(f"Sum of r_ energy terms for first variant : {df.loc[0, df.columns.str.startswith('r_')][1:].sum():.4f}")
print(f"    Total energy terms for first variant : {df.loc[0, 'r_total_score']:.4f}")

Sum of r_ energy terms for first variant : -857.9450
    Total energy terms for first variant : -857.9430

In [12]:
# The same thing isn't true for the d_ scores
# drop the first d_energy term (d_total_score) and sum up the other d_ energy terms
# we do not get something very close to the d_total_score
print(f"Sum of d_ energy terms for first variant : {df.loc[0, df.columns.str.startswith('d_')][1:].sum():.4f}")
print(f"    Total energy terms for first variant : {df.loc[0, 'd_total_score']:.4f}")

Sum of d_ energy terms for first variant : -1010.2990
    Total energy terms for first variant : -900.9790

In [13]:
with pd.option_context("display.max_rows", 1000):
    display(df.describe().transpose())

,count,mean,std,min,25%,50%,75%,max
r_total_score,100000.0,-855.129265,20.501256,-887.225,-861.69700,-856.9500,-851.28575,28.101
r_dslf_fa13,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
r_fa_atr,100000.0,-1560.950925,7.664767,-1654.659,-1565.67600,-1561.0220,-1556.20975,-1520.674
r_fa_dun,100000.0,315.848786,3.634320,301.594,313.35900,315.6800,318.13700,340.720
r_fa_elec,100000.0,-537.106482,5.717072,-566.892,-540.28400,-536.9220,-533.53400,-503.496
r_fa_intra_rep,100000.0,2.851107,0.047701,2.708,2.82100,2.8470,2.87500,4.199
r_fa_intra_sol_xover4,100000.0,55.399383,0.717147,51.867,54.96700,55.4370,55.86200,61.722
r_fa_rep,100000.0,184.715443,18.397274,174.592,182.27500,183.6870,185.35900,1066.617
r_fa_sol,100000.0,929.772388,7.763332,890.560,924.63700,929.5630,934.70800,966.306
r_hbond_bb_sc,100000.0,-55.903234,1.413368,-63.683,-56.67300,-55.9920,-55.15900,-47.971
r_hbond_lr_bb,100000.0,-82.842676,0.970326,-85.744,-83.43000,-83.0730,-82.55700,-73.335
r_hbond_sc,100000.0,-47.589054,1.759921,-56.459,-48.67500,-47.7610,-46.59900,-35.988
r_hbond_sr_bb,100000.0,-73.789411,0.765062,-77.955,-74.22600,-73.7355,-73.36900,-67.948
r_lk_ball_wtd,100000.0,-37.007585,1.026737,-41.990,-37.66400,-36.9980,-36.34300,-29.734
r_omega,100000.0,36.116661,1.353282,25.932,35.34000,36.0460,36.76425,61.740
r_p_aa_pp,100000.0,-49.628376,1.326307,-57.697,-50.33900,-49.5970,-48.86800,-36.790
r_pro_close,100000.0,1.408308,1.052960,0.535,1.22000,1.2880,1.35900,70.619
r_rama_prepro,100000.0,-21.567161,3.305932,-29.546,-23.19000,-22.3830,-21.39900,10.569
r_ref,100000.0,84.746877,4.076285,69.980,81.92400,84.7040,87.53800,101.172
r_yhh_planarity,100000.0,0.396679,0.079570,0.000,0.34800,0.4030,0.42500,1.539
d_total_score,100000.0,-894.451894,13.206732,-916.998,-899.31300,-895.6740,-891.45400,-329.764
d_Grid_score,100000.0,-30.783850,0.448789,-31.000,-31.00000,-31.0000,-31.00000,-27.000
d_Transform_accept_ratio,100000.0,0.770070,0.031136,0.444,0.75200,0.7720,0.79200,0.870
d_angle_constraint,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_atom_pair_constraint,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_chainbreak,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_classic_grid_X,100000.0,-28.909970,1.599328,-31.000,-30.00000,-29.0000,-28.00000,-15.000
d_coordinate_constraint,100000.0,0.837472,0.312282,0.093,0.64400,0.8030,0.99200,16.030
d_dihedral_constraint,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_dslf_ca_dih,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_dslf_cs_ang,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_dslf_ss_dih,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_dslf_ss_dst,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_fa_atr,100000.0,-1042.565596,5.785704,-1094.158,-1046.31100,-1042.7060,-1038.95200,-1010.298
d_fa_dun,100000.0,134.881459,2.017164,127.400,133.54000,134.7360,136.05600,158.549
d_fa_elec,100000.0,-45.106734,0.834128,-49.302,-45.67100,-45.1500,-44.59800,-39.128
d_fa_pair,100000.0,-35.703700,1.249472,-42.948,-36.47700,-35.6500,-34.89600,-30.196
d_fa_rep,100000.0,107.250415,10.918015,98.778,105.22500,106.5340,108.13700,670.358
d_fa_sol,100000.0,486.059777,3.881415,467.749,483.50200,486.0450,488.62500,505.345
d_hbond_bb_sc,100000.0,-66.387721,2.345413,-78.227,-67.86500,-66.3230,-64.89600,-52.402
d_hbond_lr_bb,100000.0,-166.047967,2.423603,-171.564,-167.48300,-166.5970,-165.44700,-146.061
d_hbond_sc,100000.0,-60.689928,3.178780,-73.475,-62.88400,-60.7890,-58.64700,-44.819
d_hbond_sr_bb,100000.0,-173.252347,1.854606,-182.060,-174.34600,-173.2955,-172.27700,-159.900
d_if_X_angle_constraint,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_atom_pair_constraint,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_chainbreak,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_coordinate_constraint,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_dihedral_constraint,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_dslf_ca_dih,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_dslf_cs_ang,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_dslf_ss_dih,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_dslf_ss_dst,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_fa_atr,100000.0,-10.246217,1.858786,-19.513,-11.40325,-10.1440,-8.95900,-4.522
d_if_X_fa_dun,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_fa_elec,100000.0,-1.087058,0.481465,-6.450,-1.30200,-1.0370,-0.77200,0.316
d_if_X_fa_pair,100000.0,-0.001132,0.092174,-1.784,0.00000,0.0000,0.00000,1.006
d_if_X_fa_rep,100000.0,0.672605,0.387920,0.015,0.39200,0.5930,0.87100,4.274
d_if_X_fa_sol,100000.0,7.473107,1.616771,2.119,6.34900,7.3690,8.52500,15.637
d_if_X_hbond_bb_sc,100000.0,-1.159104,1.370929,-6.004,-1.97425,-0.4070,-0.34400,0.000
d_if_X_hbond_lr_bb,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_hbond_sc,100000.0,-4.141570,1.865217,-13.061,-5.41600,-4.2170,-2.73100,0.000
d_if_X_hbond_sr_bb,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_omega,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_p_aa_pp,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_pro_close,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_if_X_ref,100000.0,0.000000,0.000000,0.000,0.00000,0.0000,0.00000,0.000
d_interface_delta_X,100000.0,-8.489370,1.643567,-19.226,-9.55500,-8.4480,-7.35800,-1.700
d_ligand_is_touching_X,100000.0,0.999990,0.003162,0.000,1.00000,1.0000,1.00000,1.000
d_omega,100000.0,48.804253,1.400006,36.777,48.05200,48.7930,49.51400,86.486
d_p_aa_pp,100000.0,-41.481093,1.105735,-48.201,-42.10500,-41.4810,-40.83600,-34.924
d_pro_close,100000.0,1.105949,0.811245,0.396,0.95700,1.0130,1.07200,56.649
d_ref,100000.0,-42.156134,2.177107,-51.930,-43.48000,-42.2700,-40.81000,-31.840
d_total_score_X,100000.0,-28.909970,1.599328,-31.000,-30.00000,-29.0000,-28.00000,-15.000